export const ORGANIZATIONS = [
  'Ahal awtomobil ýollaryny ulanyş müdirligi',
  'Balkan awtomobil ýollaryny ulanyş müdirligi',
  'Daşoguz awtomobil ýollaryny ulanyş müdirligi',
  'Lebap awtomobil ýollaryny ulanyş müdirligi',
  'Mary awtomobil ýollaryny ulanyş müdirligi',
  'Köpri gurluşyk müdirligi',
  '"Türkmenýoltaslama" taslama instituty',
  'Awtomobil ýollary gurmak we ulanmak boýunça Baş gözegçilik müdirligi',
  'Ýöriteleşdirilen abatlaýyş we ulanyş kärhanasy',
  'Aşgabatdaky ýöriteleşdirilen gurluşyk-gurnama we önümçilik kärhanasy',
  'Daşoguzdaky ýöriteleşdirilen gurluşyk-gurnama we önümçilik kärhanasy',
  'Aşgabat ýol gurluşyk, abatlaýyş we önümçilik kärhanasy',
  'Ahal ýol gurluşyk, abatlaýyş we önümçilik kärhanasy',
  'Balkan ýol gurluşyk, abatlaýyş we önümçilik kärhanasy',
  'Daşoguz ýol gurluşyk, abatlaýyş we önümçilik kärhanasy',
  'Lebap ýol gurluşyk, abatlaýyş we önümçilik kärhanasy',
  'Mary ýol gurluşyk, abatlaýyş we önümçilik kärhanasy',
  'Gowşutdaky ýol gurluşyk kärhanasy',
] as const;
